name: Build
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build APK
        run: ./setup-react-native-app.sh 0.72.0-rc.1 true thousand-texts
      - name: Push APK update
        run: |
          git config --global user.email "bam.flashlight@gmail.com"
          git config --global user.name "flashlight-bot"
          git add apks
          git push
