name: Build
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "18"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build APK
        run: ./setup-react-native-app.sh 0.72.0-rc.1 true thousand-texts
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Push APK update
        run: |
          git config --global user.email "bam.flashlight@gmail.com"
          git config --global user.name "flashlight-bot"
          git add apks
          git commit -m "add apks"
          git push
